# ==============================
# UTILZ Plugin Config (ThrowableFireball)
# ==============================

# ------------------------------
# Fireball Settings
# ------------------------------
cooldown: 1          # Cooldown time in seconds between throwing fireballs
fireball-speed: 2.5  # Velocity multiplier of thrown fireballs
fireball-yield: 0.8   # Explosion yield (size) of fireballs
fireball-damage-percent: 80 # Percentage of original damage dealt to entities (1-100)
fireball-knockback: 1         # Knockback strength applied to players hit by fireball

# ------------------------------
# Messages
# ------------------------------
messages:
  cooldown: "§cCurrently on cooldown"  # Message displayed when player is on cooldown

# ------------------------------
# BridgeEgg Settings
# ------------------------------
bridge-delay: 2      # Ticks before bridge generation starts after throwing
bridge-width: 1.5       # Width of the bridge in blocks (total width, centered)
bridge-block: true     # Enable block placement for bridge
bridge-entity: false   # Enable entity spawning along the bridge
bridge-block-delay: 2  # Interval in ticks between placing bridge blocks
bridge-entity-delay: 1 # Interval in ticks between spawning bridge entities

# Types of blocks to place for bridge (cycles through list)
bridge-block-types:
  - WHITE_WOOL

# Types of entities to spawn for bridge
# Format: EntityType[option1=value1;option2=value2;...]
# Supports:
#  - FallingBlock[block=BLOCK_TYPE;motion=[x,y,z]]  -> drops a block falling along the bridge
#  - Item[material=ITEM_TYPE;motion=[x,y,z]]        -> drops an item entity
#  - TNT[delay=SECONDS;motion=[x,y,z]]             -> spawns primed TNT with fuse delay
#  - Firework[color=#HEX;colorFade=#HEX;power=INT;motion=[x,y,z]] -> spawns a firework with optional color and motion
bridge-entity-types:
  - FIREWORK[color=#FF0000;power=2;motion=[0,1,0]] # Red firework shooting upward

# ------------------------------
# Auto TNT Settings
# ------------------------------
tnt-duration: 3         # Fuse duration in seconds for Auto TNT when placed
tnt-damage-percent: 50  # Percentage of normal TNT damage dealt to entities
